In [9]:
import pandas as pd
from pandas import Series, DataFrame

In [13]:
df=pd.read_csv('aa.csv')
df

,A1,A2,A3,A4,A5,A6,A7,A8,A9,A10
0,PLC8,PLC8-BASE-CIP,21012,1071-X-779,1071-XY-779,FIELDBUS,A21-PB-02-34,EX,F02,B
1,PLC8,PLC8-BASE-CIP,21014,1071-X-779,1071-ZSH-779,HARDWIRED,A21-PB-02-34,NO,F02,B
2,PLC8,PLC8-BASE-CIP,21016,1071-X-779,1071-ZSL-779,HARDWIRED,A21-PB-02-34,NO,F02,B
3,PLC8,PLC8-BASE-CIP,21019,1071-X-780,1071-XY-780,FIELDBUS,A21-PB-02-34,EX,F02,B
4,PLC8,PLC8-BASE-CIP,21021,1071-X-780,1071-ZSH-780,HARDWIRED,A21-PB-02-34,NO,F02,B
5,PLC8,PLC8-BASE-CIP,21023,1071-X-780,1071-ZSL-780,HARDWIRED,A21-PB-02-34,NO,F02,B
6,PLC8,PLC8-BASE-CIP,21026,1072-X-777,1072-XY-777,FIELDBUS,A21-PB-02-34,EX,F02,B
7,PLC8,PLC8-BASE-CIP,21028,1072-X-777,1072-ZSH-777,HARDWIRED,A21-PB-02-34,NO,F02,B
8,PLC8,PLC8-BASE-CIP,21030,1072-X-777,1072-ZSL-777,HARDWIRED,A21-PB-02-34,NO,F02,B
9,PLC8,PLC8-BASE-CIP,21033,1072-X-779,1072-XY-779,FIELDBUS,A21-PB-02-34,EX,F02,B
10,PLC8,PLC8-BASE-CIP,21035,1072-X-779,1072-ZSH-779,HARDWIRED,A21-PB-02-34,NO,F02,B
11,PLC8,PLC8-BASE-CIP,21037,1072-X-779,1072-ZSL-779,HARDWIRED,A21-PB-02-34,NO,F02,B

In [21]:
df1=pd.read_excel('aa.xlsx')#默认只能读第一个表单的数据，没数据的行会直接填充NaN, 列名是第一行的数据.
df1

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12
0,PLC8,PLC8-BASE-CIP,20995,1070-X-780,1070-ZSL-780,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
1,PLC8,PLC8-BASE-CIP,20998,1071-X-776,1071-XY-776,FIELDBUS,NaN,A21-PB-02-34,EX,F02,NaN,B
2,PLC8,PLC8-BASE-CIP,21000,1071-X-776,1071-ZSH-776,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
3,PLC8,PLC8-BASE-CIP,21002,1071-X-776,1071-ZSL-776,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
4,PLC8,PLC8-BASE-CIP,21005,1071-X-777,1071-XY-777,FIELDBUS,NaN,A21-PB-02-34,EX,F02,NaN,B
5,PLC8,PLC8-BASE-CIP,21007,1071-X-777,1071-ZSH-777,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
6,PLC8,PLC8-BASE-CIP,21009,1071-X-777,1071-ZSL-777,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B

In [22]:
df1.to_csv('write1.csv') # 直接数据写到CSV中

In [23]:
df1.to_html('aa.html')

In [24]:
df1.to_json('aa.json')

JSON的章节

In [26]:
import json

#result=json.loads(obj) #只能用于导入固定JSON数据格式的对象

In [28]:
data=pd.read_json('aa.json')
print(data.to_json())

{"C1":{"0":"PLC8","1":"PLC8","2":"PLC8","3":"PLC8","4":"PLC8","5":"PLC8","6":"PLC8"},"C2":{"0":"PLC8-BASE-CIP","1":"PLC8-BASE-CIP","2":"PLC8-BASE-CIP","3":"PLC8-BASE-CIP","4":"PLC8-BASE-CIP","5":"PLC8-BASE-CIP","6":"PLC8-BASE-CIP"},"C3":{"0":20995,"1":20998,"2":21000,"3":21002,"4":21005,"5":21007,"6":21009},"C4":{"0":"1070-X-780","1":"1071-X-776","2":"1071-X-776","3":"1071-X-776","4":"1071-X-777","5":"1071-X-777","6":"1071-X-777"},"C5":{"0":"1070-ZSL-780","1":"1071-XY-776","2":"1071-ZSH-776","3":"1071-ZSL-776","4":"1071-XY-777","5":"1071-ZSH-777","6":"1071-ZSL-777"},"C6":{"0":"HARDWIRED","1":"FIELDBUS","2":"HARDWIRED","3":"HARDWIRED","4":"FIELDBUS","5":"HARDWIRED","6":"HARDWIRED"},"C7":{"0":null,"1":null,"2":null,"3":null,"4":null,"5":null,"6":null},"C8":{"0":"A21-PB-02-34","1":"A21-PB-02-34","2":"A21-PB-02-34","3":"A21-PB-02-34","4":"A21-PB-02-34","5":"A21-PB-02-34","6":"A21-PB-02-34"},"C9":{"0":"NO","1":"EX","2":"NO","3":"NO","4":"EX","5":"NO","6":"NO"},"C10":{"0":"F02","1":"F02","2":"F02","3":"F02","4":"F02","5":"F02","6":"F02"},"C11":{"0":null,"1":null,"2":null,"3":null,"4":null,"5":null,"6":null},"C12":{"0":"B","1":"B","2":"B","3":"B","4":"B","5":"B","6":"B"}}

In [32]:
tables=pd.read_html('aa.html')
len(tables)

1

In [34]:
failures=tables[0]
failures.head()

,Unnamed: 0,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12
0,0,PLC8,PLC8-BASE-CIP,20995,1070-X-780,1070-ZSL-780,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
1,1,PLC8,PLC8-BASE-CIP,20998,1071-X-776,1071-XY-776,FIELDBUS,NaN,A21-PB-02-34,EX,F02,NaN,B
2,2,PLC8,PLC8-BASE-CIP,21000,1071-X-776,1071-ZSH-776,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
3,3,PLC8,PLC8-BASE-CIP,21002,1071-X-776,1071-ZSL-776,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
4,4,PLC8,PLC8-BASE-CIP,21005,1071-X-777,1071-XY-777,FIELDBUS,NaN,A21-PB-02-34,EX,F02,NaN,B

XML章节

二进制格式 PICKLE化：临时数据
HDF5 (推荐）
MESSAGEPACK

In [39]:
store=pd.HDFStore('mydata.h5')

In [40]:
pd.read_hdf('mydata.h5','obj5')

ValueError: The file 'mydata.h5' is already opened, but not in read-only mode (as requested).

EXCEL读写

In [56]:
xlsx=pd.ExcelFile('aa.xlsx')
frame=pd.read_excel(xlsx,'S1') #读取指定目标表格的数据
frame

,C1,C2,C3,C4,C5,C6,C7,C8,C9,C10,C11,C12
0,PLC8,PLC8-BASE-CIP,20995,1070-X-780,1070-ZSL-780,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
1,PLC8,PLC8-BASE-CIP,20998,1071-X-776,1071-XY-776,FIELDBUS,NaN,A21-PB-02-34,EX,F02,NaN,B
2,PLC8,PLC8-BASE-CIP,21000,1071-X-776,1071-ZSH-776,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
3,PLC8,PLC8-BASE-CIP,21002,1071-X-776,1071-ZSL-776,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
4,PLC8,PLC8-BASE-CIP,21005,1071-X-777,1071-XY-777,FIELDBUS,NaN,A21-PB-02-34,EX,F02,NaN,B
5,PLC8,PLC8-BASE-CIP,21007,1071-X-777,1071-ZSH-777,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B
6,PLC8,PLC8-BASE-CIP,21009,1071-X-777,1071-ZSL-777,HARDWIRED,NaN,A21-PB-02-34,NO,F02,NaN,B

In [60]:
writer=pd.ExcelWriter('bb1.xlsx')
frame.to_excel(writer,'sheet11') #可以定义新EXCEL表格的SHEET名称
writer.save()

WEB API

In [75]:
import requests
url='http://api.github.com/repos/pandas-dev/pandas/issues'
#url='https://www.baidu.com/'
resp=requests.get(url)
resp

In [82]:
data=resp.json()
data
data[1]['title'] 
issues=pd.DataFrame(data,columns=['title','state','locked'])
issues

                                                title state  locked
0   resample using for subsample will regards NaN ...  open   False
1         MemoryError when using `.drop_duplicates()`  open   False
2       TST: new test for incorrect series assignment  open   False
3            CLN: deprivatize factorize_from_iterable  open   False
4   TST: new test for sort index when Nan in other...  open   False
5                       Deprecate using `xlrd` engine  open   False
6                      Updated index links for 0.25.3  open   False
7             Add documentation linking to sqlalchemy  open   False
8   TST: new test for str to small float conversio...  open   False
9   TST: Adding merge test for non-string columns ...  open   False
10                                      Fix pipe docs  open   False
11  29213: Dataframe Constructor from List of List...  open   False
12                Test added: uint64 multicolumn sort  open   False
13        26302 add typing to assert star equal funcs  open   False
14     Disallow non-scalar fill_value in maybe_upcast  open   False
15     TYPING: scalar type that matches lib.is_scalar  open   False
16  GH 16051: DataFrame.replace() overwrites when ...  open   False
17  ensure consistent structure for groupby on ind...  open   False
18     TST: new test for subset of a MultiIndex dtype  open   False
19  TST: Test type issue fix in empty groupby from...  open   False
20  BUG: Issue #29128 Series.var not returning the...  open   False
21  TST: Add test to check category dtype remains ...  open   False
22  Local test failure: AssertionError: Series are...  open   False
23  GH14422: BUG: to_numeric doesn't work uint64 n...  open   False
24  TST: Adding styler applymap multindex & code t...  open   False
25                           black==19.10b0 breaks CI  open   False
26  Fix mypy error messages in pandas/test/tseries...  open   False
27  TST: Adding to_dict numeric consistency test (...  open   False
28                               Remove FrozenNDArray  open   False
29  BUG: assignment to multiple columns when some ...  open   False

SQL 的连接和数据抽取?? 如何连接到SQL数据库待定？？？？

In [90]:
import sqlite3
query="""
    CREATE TABLE TEST
    (a VARCHAR(20),B VARCHAR(20),C VARCHAR(20),D VARCHAR(20))
    );"""
con=sqlite3.connect('mydata.sqlite')
con.execute(query)

OperationalError: near ")": syntax error

In [91]:
import sqlalchemy as sqla
db=sqla.create_engine('sqlite:///mydata.sqlite')
pd.read_sql('select * from test', db)

OperationalError: (sqlite3.OperationalError) no such table: test [SQL: 'select * from test'] (Background on this error at: http://sqlalche.me/e/e3q8)